### ISSUE TITLE
Subject not displaying in IE

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/old-weather#77]
Found by @srallen in #73. The loading state isn't being updated, as its end is triggered by `ng-load`, which is waiting for the `load` event from the image to fire. This never happens, as in IE, the event is called `SVGLoad`. 

We could patch `ng-load` to listen for the `SVGLoad` event as well, or we could use image preloading to determine when to show the subject.

**Comment by srallen** [comment]
Let me know if you still need any help with IE testing or working on this specific issue. I may not be as quick as I could be with debugging since I've been learning Angular as I do it, but I'll help out if you need it.

**Comment by rogerhutchings** [comment]
If you're happy to take this issue on, that'd be hugely appreciated.

**Comment by srallen** [comment]
@rogerhutchings, I have a start of a solution in [this branch](https://github.com/zooniverse/old-weather/tree/ie-svg-load) with a fork of ng-load [seen here](https://github.com/srallen/ng-load). I'm not sure if what I'm doing is causing more issues. My changes in the fork get the subject to load in Edge but not IE11. In Edge, it loads, but the drawing task doesn't work. 

Another idea was to take out ng-load and use a standard `onload` on the SVG image element itself and interpolate a handler into it. This works, but angular puts out an error to the console saying not to do that and to use a ng- version instead. This I find annoying since ng-load isn't a part of core and looks like it won't be.

**Comment by rogerhutchings** [comment]
Nice work! Don't worry about the drawing tasks for now, I'm fairly confident I have a fix (#79) - if you can get a subject to load in IE11, I'll be very happy.
- I don't think `restrict: A` needs to be taken out - all that does is restrict the directive to being instantiated via an attribute, which would be the way you'd do it anyway, it doesn't need to be an element or class.
- I like the idea of taking out ng-load, as I don't think it's used anywhere else. What does the interpolated attribute look like? There's a generic handler prefix available, so if it's the error I think it is, you can use `ng-attr-foo="{{ bar }}"`, which should suppress that error.
